name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2

    - name: Step 2 - Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Step 3 - Maven build
      run: mvn clean package

    - name: Step 4 - Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Step 5 - Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker:latest

    - name: Step 6 - Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
